import {test,expect,type Page} from '@playwright/test';
import {freshSave} from '../../src/core/state';
import {SAVE_KEY} from '../../src/core/save';
const read=(p:Page)=>p.evaluate(()=>Reflect.get(window,'__SINBAD_TEST__'));
async function walk(p:Page,x:number){const end=Date.now()+25000;let jump=0;for(;;){if(Date.now()>end)throw Error(`Cannot reach ${x}: ${JSON.stringify(await read(p))}`);const s=await read(p);if(!s.player){await p.waitForTimeout(50);continue;}if(Math.abs(s.player.x-x)<12)break;const key=s.player.x<x?'d':'a';await p.keyboard.up(key==='d'?'a':'d');await p.keyboard.down(key);if(Date.now()-jump>430){await p.keyboard.press('ArrowUp');jump=Date.now();}await p.waitForTimeout(60);}await p.keyboard.up('a');await p.keyboard.up('d');await expect.poll(async()=>!!(await read(p)).player?.grounded).toBe(true);}
async function use(p:Page,x:number){await walk(p,x);await p.keyboard.press('e');await p.waitForTimeout(150);}
test('S07 save → mirror reset and safe puzzle → T02 reload, illusion and optional journal',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url());});
 const s=freshSave();s.clearedStageIds=['S01','S02','S03','S04','S05','S06','S07'];s.checkpoint={stageId:'S07',checkpointId:'cave'};s.flags=['bubbleBlessing','genieCave'];s.treasures=['T01'];s.weapons.push('W02','W03');s.equippedSkill='flamePulse';s.totalXp=400;
 await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);},{key:SAVE_KEY,value:JSON.stringify(s)});await page.goto('/');await page.getByRole('button',{name:'이어하기 · S07'}).click();await page.getByRole('button',{name:'가방과 지도'}).click();await page.locator('[data-stage="S08"]').click();await expect.poll(async()=>(await read(page)).stage).toBe('S08');
 await use(page,220);await page.getByRole('button',{name:'전체 생략'}).click();await walk(page,1435);const hp=(await read(page)).player.hp;await page.waitForTimeout(3500);expect((await read(page)).player.hp).toBe(hp);expect((await read(page)).puzzleSafe).toBe(true);
 await use(page,1530);expect((await read(page)).save.journalPageIds).toEqual([]);
 await use(page,1650);expect((await read(page)).mirrors).toEqual([1,0,0]);await page.getByRole('button',{name:'거울 초기화',exact:true}).click();expect((await read(page)).mirrors).toEqual([0,0,0]);
 await use(page,2460);await page.keyboard.down('d');await page.keyboard.press('ArrowUp');await page.waitForTimeout(1000);await page.keyboard.up('d');expect((await read(page)).player.x).toBeLessThan(2500);expect((await read(page)).save.treasures).not.toContain('T02');
 await use(page,1650);await use(page,1940);await page.keyboard.press('e');await page.waitForTimeout(100);await page.keyboard.press('e');await page.waitForTimeout(100);await use(page,2230);await page.keyboard.press('e');await expect.poll(async()=>(await read(page)).save.completedObjectiveIds.includes('S08.light')).toBe(true);
 await page.screenshot({path:info.outputPath('S08-mirrors.png')});await page.reload();await page.getByRole('button',{name:'이어하기 · S08'}).click();await expect.poll(async()=>(await read(page)).connectedMirrors).toBe(3);
 await use(page,2690);await expect(page.getByTestId('dialogue-text')).toBeVisible();expect((await read(page)).save.treasures).toContain('T02');expect((await read(page)).save.equippedSkill).toBe('flamePulse');await page.reload();await page.getByRole('button',{name:'이어하기 · S08'}).click();await expect.poll(async()=>(await read(page)).save.checkpoint.checkpointId).toBe('gift');
 await use(page,2690);await page.getByRole('button',{name:'전체 생략'}).click();await page.getByRole('button',{name:'거울 초기화',exact:true}).click();expect((await read(page)).connectedMirrors).toBe(3);
 await use(page,3000);await expect(page.getByTestId('dialogue-text')).toContainText('탑');await page.getByRole('button',{name:'전체 생략'}).click();expect((await read(page)).save.completedObjectiveIds).toContain('S08.starMap');
 await walk(page,1530);await page.screenshot({path:info.outputPath('S08-hidden-journal.png')});const mp=(await read(page)).mp;await page.keyboard.press('e');await expect(page.getByTestId('dialogue-text')).toBeVisible();expect((await read(page)).mp).toBe(mp);await page.getByRole('button',{name:'전체 생략'}).click();expect((await read(page)).save.journalPageIds).toEqual(['S08.journal']);await page.keyboard.press('e');await page.getByRole('button',{name:'전체 생략'}).click();expect((await read(page)).save.journalPageIds).toEqual(['S08.journal']);
 await use(page,3500);await page.getByRole('button',{name:'다음 스테이지'}).click();await expect.poll(async()=>(await read(page)).stage).toBe('S09');expect((await read(page)).save.clearedStageIds).toContain('S08');expect(errors).toEqual([]);
});
